<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$objectManager=\Magento\Framework\App\ObjectManager::getInstance();
/**
 * @var $orderItemRepos \Cleargo\Clearomni\Model\OrderItemRepository
 */
$orderItemRepos=$objectManager->get('Cleargo\Clearomni\Model\OrderItemRepository');
?>
<?php if ($_item = $block->getItem()): ?>
    <?php
    try {
        $item = $orderItemRepos->getByItemId($_item->getItemId());
    }catch(\Exception $e){
        $item=null;
    }
    ?>
<table class="qty-table">
    <tr>
        <th><?= /* @escapeNotVerified */ __('Ordered') ?></th>
        <td><?= /* @escapeNotVerified */ $_item->getQtyOrdered()*1 ?></td>
    </tr>

    <?php if ((float) $_item->getQtyInvoiced()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Invoiced') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyInvoiced()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $_item->getQtyShipped()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Shipped') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyShipped()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $_item->getQtyRefunded()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Refunded') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyRefunded()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $_item->getQtyCanceled()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Canceled') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyCanceled()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if(isset($item)):?>
        <?php foreach ($item->getItemData() as $key=>$value):?>
            <?php if((float)$value):?>
                <tr>
                    <th><?= /* @escapeNotVerified */ __($key) ?></th>
                    <td><?= /* @escapeNotVerified */ $value*1 ?></td>
                </tr>
            <?php endif;?>
        <?php endforeach; ?>
    <?php endif; ?>
</table>
<?php endif; ?>
