<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$objectManager=\Magento\Framework\App\ObjectManager::getInstance();
/**
 * @var $orderItemRepos \Cleargo\Clearomni\Model\OrderItemRepository
 */
$orderItemRepos=$objectManager->get('Cleargo\Clearomni\Model\OrderItemRepository');
?>
<?php if ($_item = $block->getItem()): ?>
    <?php
        $item=$orderItemRepos->getByItemId($_item->getItemId());
    ?>
<table class="qty-table">
    <tr>
        <th><?= /* @escapeNotVerified */ __('Ordered') ?></th>
        <td><?= /* @escapeNotVerified */ $_item->getQtyOrdered()*1 ?></td>
    </tr>

    <?php if ((float) $_item->getQtyInvoiced()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Invoiced') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyInvoiced()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $_item->getQtyShipped()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Shipped') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyShipped()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $_item->getQtyRefunded()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Refunded') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyRefunded()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if ((float) $_item->getQtyCanceled()): ?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Canceled') ?></th>
            <td><?= /* @escapeNotVerified */ $_item->getQtyCanceled()*1 ?></td>
        </tr>
    <?php endif; ?>

    <?php if((float)$item->getQtyClearomniRefunded()):?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Clearomni Refunded') ?></th>
            <td><?= /* @escapeNotVerified */ $item->getQtyClearomniRefunded()*1 ?></td>
        </tr>
    <?php endif;?>
    <?php if((float)$item->getQtyClearomniCancelled()):?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Clearomni Cancelled') ?></th>
            <td><?= /* @escapeNotVerified */ $item->getQtyClearomniCancelled()*1 ?></td>
        </tr>
    <?php endif;?>
    <?php if((float)$item->getQtyClearomniCompleted()):?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Clearomni Completed') ?></th>
            <td><?= /* @escapeNotVerified */ $item->getQtyClearomniCompleted()*1 ?></td>
        </tr>
    <?php endif;?>
    <?php if((float)$item->getQtyClearomniExchangeRejected()):?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Clearomni Exchange Rejected') ?></th>
            <td><?= /* @escapeNotVerified */ $item->getQtyClearomniExchangeRejected()*1 ?></td>
        </tr>
    <?php endif;?>
    <?php if((float)$item->getQtyClearomniExchangeSuccess()):?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Clearomni Exchange Success') ?></th>
            <td><?= /* @escapeNotVerified */ $item->getQtyClearomniExchangeSuccess()*1 ?></td>
        </tr>
    <?php endif;?>
    <?php if((float)$item->getQtyClearomniReserved()):?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Clearomni Reserved') ?></th>
            <td><?= /* @escapeNotVerified */ $item->getQtyClearomniReserved()*1 ?></td>
        </tr>
    <?php endif;?>
    <?php if((float)$item->getQtyClearomniToTransfer()):?>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Clearomni To Transfer') ?></th>
            <td><?= /* @escapeNotVerified */ $item->getQtyClearomniToTransfer()*1 ?></td>
        </tr>
    <?php endif;?>
</table>
<?php endif; ?>
